In [1]:
import pandas as pd

In [2]:
# Define file path
sim_features_path = "../results/similarity_features.csv"
label_file_path = '../../Dataset/CodeAid_Source_Codes_Labeling.xlsx'
output_path = "../results/merge_features_and_label.csv"

# Load dataset
sim_features = pd.read_csv(sim_features_path)
label_file = pd.read_excel(label_file_path)

In [3]:
sim_features

,coding_problem_id,llm_answer_id,candidate_word_count,ai_word_count,shared_tokens,candidate_seq,ai_generated_seq,cosine_similarity,jaccard_similarity,levenshtein_similarity
0,source_code_000,3.5-turbo_00,25,49,6,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 2594, 79, 125, 113, 83, 15, 269, 19, ...",0.381229,0.153846,0.010000
1,source_code_000,3.5-turbo_01,25,49,5,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 19, 84...",0.113747,0.142857,0.010417
2,source_code_000,4-turbo_00,25,112,9,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 19, 31...",0.292639,0.152542,0.003425
3,source_code_000,4-turbo_01,25,92,8,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 1242, 79, 125, 113, 83, 15, 269, 19, ...",0.351370,0.140351,0.004237
4,source_code_000,4_00,25,68,6,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 358, 2...",0.327755,0.120000,0.006410
...,...,...,...,...,...,...,...,...,...,...
373,source_code_062,3.5-turbo_01,131,109,31,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2586, 17, 17, 1767, 17, 422, 17, 15,...",0.566800,0.274336,0.003788
374,source_code_062,4-turbo_00,131,103,27,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2015, 40, 1327, 2, 40, 1198, 247, 20...",0.580553,0.228814,0.003745
375,source_code_062,4-turbo_01,131,142,30,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 13, 77, 2, 480, 1077, 1122, 591, 114...",0.502546,0.229008,0.003401
376,source_code_062,4_00,131,113,25,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[18, 2592, 17, 258, 632, 20, 422, 15, 13, 825,...",0.424932,0.210084,0.003559
377,source_code_062,4_01,131,134,25,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2593, 17, 825, 2, 17, 20, 258, 632, ...",0.409349,0.203252,0.003257

In [4]:
label_file

    coding_problem_id     llm_answer_id  plagiarism_score
0     source_code_000  gpt-3.5-turbo_00               0.0
1     source_code_000  gpt-3.5-turbo_01               0.0
2     source_code_000          gpt-4_00               0.0
3     source_code_000          gpt-4_01               0.0
4     source_code_000    gpt-4-turbo_00               0.0
..                ...               ...               ...
373   source_code_062  gpt-3.5-turbo_01               0.3
374   source_code_062          gpt-4_00               0.3
375   source_code_062          gpt-4_01               0.3
376   source_code_062    gpt-4-turbo_00               0.3
377   source_code_062    gpt-4-turbo_01               0.3

[378 rows x 3 columns]

In [8]:
pl_score = label_file['plagiarism_score']

In [10]:
sim_features['plagiarism_score'] = pl_score

In [11]:
sim_features

,coding_problem_id,llm_answer_id,candidate_word_count,ai_word_count,shared_tokens,candidate_seq,ai_generated_seq,cosine_similarity,jaccard_similarity,levenshtein_similarity,plagiarism_score
0,source_code_000,3.5-turbo_00,25,49,6,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 2594, 79, 125, 113, 83, 15, 269, 19, ...",0.381229,0.153846,0.010000,0.0
1,source_code_000,3.5-turbo_01,25,49,5,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 19, 84...",0.113747,0.142857,0.010417,0.0
2,source_code_000,4-turbo_00,25,112,9,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 19, 31...",0.292639,0.152542,0.003425,0.0
3,source_code_000,4-turbo_01,25,92,8,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 1242, 79, 125, 113, 83, 15, 269, 19, ...",0.351370,0.140351,0.004237,0.0
4,source_code_000,4_00,25,68,6,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 358, 2...",0.327755,0.120000,0.006410,0.0
...,...,...,...,...,...,...,...,...,...,...,...
373,source_code_062,3.5-turbo_01,131,109,31,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2586, 17, 17, 1767, 17, 422, 17, 15,...",0.566800,0.274336,0.003788,0.3
374,source_code_062,4-turbo_00,131,103,27,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2015, 40, 1327, 2, 40, 1198, 247, 20...",0.580553,0.228814,0.003745,0.3
375,source_code_062,4-turbo_01,131,142,30,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 13, 77, 2, 480, 1077, 1122, 591, 114...",0.502546,0.229008,0.003401,0.3
376,source_code_062,4_00,131,113,25,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[18, 2592, 17, 258, 632, 20, 422, 15, 13, 825,...",0.424932,0.210084,0.003559,0.3
377,source_code_062,4_01,131,134,25,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2593, 17, 825, 2, 17, 20, 258, 632, ...",0.409349,0.203252,0.003257,0.3

In [12]:
output_path = "../results/features_with_aiscores.csv"
sim_features.to_csv(output_path, index=False)

print(f"Merged dataset saved to {output_path}")

Merged dataset saved to ../results/features_with_aiscores.csv

In [13]:
sim_features

,coding_problem_id,llm_answer_id,candidate_word_count,ai_word_count,shared_tokens,candidate_seq,ai_generated_seq,cosine_similarity,jaccard_similarity,levenshtein_similarity,plagiarism_score
0,source_code_000,3.5-turbo_00,25,49,6,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 2594, 79, 125, 113, 83, 15, 269, 19, ...",0.381229,0.153846,0.010000,0.0
1,source_code_000,3.5-turbo_01,25,49,5,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 19, 84...",0.113747,0.142857,0.010417,0.0
2,source_code_000,4-turbo_00,25,112,9,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 19, 31...",0.292639,0.152542,0.003425,0.0
3,source_code_000,4-turbo_01,25,92,8,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 1242, 79, 125, 113, 83, 15, 269, 19, ...",0.351370,0.140351,0.004237,0.0
4,source_code_000,4_00,25,68,6,"[759, 1241, 31, 1192, 19, 6, 31, 500, 4, 5, 17...","[79, 41, 83, 79, 125, 113, 83, 15, 269, 358, 2...",0.327755,0.120000,0.006410,0.0
...,...,...,...,...,...,...,...,...,...,...,...
373,source_code_062,3.5-turbo_01,131,109,31,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2586, 17, 17, 1767, 17, 422, 17, 15,...",0.566800,0.274336,0.003788,0.3
374,source_code_062,4-turbo_00,131,103,27,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2015, 40, 1327, 2, 40, 1198, 247, 20...",0.580553,0.228814,0.003745,0.3
375,source_code_062,4-turbo_01,131,142,30,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 13, 77, 2, 480, 1077, 1122, 591, 114...",0.502546,0.229008,0.003401,0.3
376,source_code_062,4_00,131,113,25,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[18, 2592, 17, 258, 632, 20, 422, 15, 13, 825,...",0.424932,0.210084,0.003559,0.3
377,source_code_062,4_01,131,134,25,"[105, 11, 1760, 106, 11, 1761, 104, 131, 9, 26...","[260, 18, 2593, 17, 825, 2, 17, 20, 258, 632, ...",0.409349,0.203252,0.003257,0.3

In [16]:

required_columns = ['cosine_similarity', 'jaccard_similarity', 'levenshtein_similarity', 'plagiarism_score']
missing_columns = [col for col in required_columns if col not in sim_features.columns]
if not missing_columns:
    print("All required columns are present!")
else:
    print(f"Missing columns: {missing_columns}")

All required columns are present!

In [17]:
print(sim_features[['cosine_similarity', 'jaccard_similarity', 'levenshtein_similarity', 'plagiarism_score']].isna().sum())

cosine_similarity         0
jaccard_similarity        0
levenshtein_similarity    0
plagiarism_score          0
dtype: int64

In [18]:
print(sim_features['plagiarism_score'].value_counts())

plagiarism_score
0.1    81
0.0    65
0.2    59
0.4    52
0.3    40
0.8    24
0.9    20
0.6    17
0.7    11
0.5     9
Name: count, dtype: int64